// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AComment: typeof import('ant-design-vue/es')['Comment']
    AdminBlogManager: typeof import('./src/views/Admin/AdminBlogManager.vue')['default']
    AdminDashboard: typeof import('./src/views/Admin/AdminDashboard.vue')['default']
    AdminHome: typeof import('./src/views/Admin/AdminHome.vue')['default']
    AdminUserManager: typeof import('./src/views/Admin/AdminUserManager.vue')['default']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Banner: typeof import('./src/views/Admin/UserMan/partials/Banner.vue')['default']
    Breadcrumb: typeof import('./src/views/Admin/UserMan/partials/Breadcrumb.vue')['default']
    CategoryLabel: typeof import('./src/components/PostList/CategoryLabel.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CreatePost: typeof import('./src/views/createPost/CreatePost.vue')['default']
    DashBoard: typeof import('./src/views/Admin/DashBoard/DashBoard.vue')['default']
    Detail: typeof import('./src/views/Detail/Detail.vue')['default']
    EmptyLayout: typeof import('./src/views/Admin/EmptyLayout.vue')['default']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    ForgotPassword: typeof import('./src/views/Auth/ForgotPassword/ForgotPassword.vue')['default']
    Header: typeof import('./src/views/Admin/Header/Header.vue')['default']
    Home: typeof import('./src/views/home/Home.vue')['default']
    Login: typeof import('./src/views/Auth/Login/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    PostList: typeof import('./src/components/PostList/PostList.vue')['default']
    Register: typeof import('./src/views/Auth/Register/Register.vue')['default']
    RichText: typeof import('./src/components/RichText/RichText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/views/Admin/SideBar/Sidebar.vue')['default']
    TextInput: typeof import('./src/components/TextInput/TextInput.vue')['default']
    UpdatePost: typeof import('./src/views/updatePost/UpdatePost.vue')['default']
    UserManager: typeof import('./src/views/Admin/UserMan/UserManager.vue')['default']
    UserProfile: typeof import('./src/views/UserProfile/UserProfile.vue')['default']
  }
}
