// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ASelect: typeof import('ant-design-vue/es')['Select']
    CategoryLabel: typeof import('./src/components/PostList/CategoryLabel.vue')['default']
    CreatePost: typeof import('./src/views/createPost/CreatePost.vue')['default']
    Footer: typeof import('./src/layout/Footer.vue')['default']
    ForgotPassword: typeof import('./src/views/Auth/ForgotPassword/ForgotPassword.vue')['default']
    Home: typeof import('./src/views/home/Home.vue')['default']
    Login: typeof import('./src/views/Auth/Login/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    PostList: typeof import('./src/components/PostList/PostList.vue')['default']
    Register: typeof import('./src/views/Auth/Register/Register.vue')['default']
    RichText: typeof import('./src/components/RichText/RichText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/TextInput/TextInput.vue')['default']
    UserProfile: typeof import('./src/views/UserProfile/UserProfile.vue')['default']
  }
}
